"""Builds a MITRE ATT&CK Navigator layer (v4.5 layer format) from
reconciled technique mappings.
"""

from typing import Any, Dict, List

_COLOR_BY_TIER = {"high": "#e60d0d", "medium": "#ffe766", "low": "#8ec843"}


def build_navigator_layer(family: str, techniques: List["MappedTechnique"], attck_version: str = "14") -> Dict[str, Any]:  # noqa: F821
    """Build a MITRE ATT&CK Navigator layer dict from a family's reconciled technique mappings.

    Args:
        family: Sample family label, used in the layer's name/description.
        techniques: Reconciled MappedTechnique list to render.
        attck_version: ATT&CK version to declare in the layer.

    Returns:
        A Navigator v4.5 layer dict, ready to serialize as JSON.
    """
    layer_techniques = []
    for t in techniques:
        evidence_strs = sorted({e.get("evidence", "") for e in t.evidence if e.get("evidence")})
        comment = f"{'+'.join(t.sources)} corroborated; evidence: {', '.join(evidence_strs)}"
        layer_techniques.append(
            {
                "techniqueID": t.technique_id,
                "score": t.confidence_score,
                "color": _COLOR_BY_TIER.get(t.final_confidence, "#8ec843"),
                "comment": comment[:500],
                "enabled": True,
                "showSubtechniques": False,
                "metadata": [
                    {"name": "confidence", "value": t.final_confidence},
                    {"name": "sources", "value": ", ".join(t.sources)},
                ],
            }
        )

    return {
        "name": f"MalWhere - {family}",
        "versions": {"attack": attck_version, "navigator": "4.9.1", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": f"Auto-generated by map_attck.py — {family} static+dynamic corroborated mapping",
        "filters": {"platforms": ["Windows"]},
        "sorting": 0,
        "layout": {"layout": "side", "showID": True, "showName": True},
        "hideDisabled": False,
        "techniques": layer_techniques,
        "gradient": {"colors": ["#8ec843", "#ffe766", "#e60d0d"], "minValue": 0, "maxValue": 100},
        "legendItems": [
            {"label": "High (cross-source corroborated or strong single-source)", "color": "#e60d0d"},
            {"label": "Medium", "color": "#ffe766"},
            {"label": "Low", "color": "#8ec843"},
        ],
        "metadata": [{"name": "generated_by", "value": "MalWhere map_attck.py"}],
    }
