"""Offline-safe MITRE ATT&CK technique name resolution.

2-tier resolution, no network or external files ever (malwhere_net is
`internal: true` -- no egress -- see docker-compose.yml; this module has no
dependency on a fetched STIX bundle either, by design -- see the dict below):
  1. Built-in fallback dict below, covering every technique ID actually
     observed across the validated samples' static+dynamic reports, plus a
     full-tactic expansion for Execution, Persistence, and Command and
     Control (the tactics a single-VM detonation sandbox can actually
     produce evidence for -- see the comment above that block).
  2. Generic "Unknown ATT&CK technique (ID)" placeholder — never fails.
"""

# Curated directly from real data: every technique ID observed in
# results/{wsnake,roning,akira}/iocs/normalized_iocs.json as of the initial
# 3-sample validation run.
TECHNIQUE_NAME_FALLBACK = {
    "T1003": "OS Credential Dumping",
    "T1005": "Data from Local System",
    "T1027": "Obfuscated Files or Information",
    "T1027.002": "Obfuscated Files or Information: Software Packing",
    "T1033": "System Owner/User Discovery",
    "T1036": "Masquerading",
    "T1047": "Windows Management Instrumentation",
    "T1053": "Scheduled Task/Job",
    "T1055": "Process Injection",
    "T1057": "Process Discovery",
    "T1059": "Command and Scripting Interpreter",
    "T1069": "Permission Groups Discovery",
    "T1070": "Indicator Removal",
    "T1070.006": "Indicator Removal: Timestomp",
    "T1071": "Application Layer Protocol",
    "T1074": "Data Staged",
    "T1082": "System Information Discovery",
    "T1083": "File and Directory Discovery",
    "T1090": "Proxy",
    "T1105": "Ingress Tool Transfer",
    "T1106": "Native API",
    "T1112": "Modify Registry",
    "T1113": "Screen Capture",
    "T1114": "Email Collection",
    "T1129": "Shared Modules",
    "T1135": "Network Share Discovery",
    "T1202": "Indirect Command Execution",
    "T1485": "Data Destruction",
    "T1486": "Data Encrypted for Impact",
    "T1489": "Service Stop",
    "T1490": "Inhibit System Recovery",
    "T1497": "Virtualization/Sandbox Evasion",
    "T1542.003": "Pre-OS Boot: Bootkit",
    "T1543": "Create or Modify System Process",
    "T1543.003": "Create or Modify System Process: Windows Service",
    "T1547": "Boot or Logon Autostart Execution",
    "T1547.001": "Boot or Logon Autostart Execution: Registry Run Keys / Startup Folder",
    "T1548": "Abuse Elevation Control Mechanism",
    "T1552": "Unsecured Credentials",
    "T1552.001": "Unsecured Credentials: Credentials In Files",
    "T1555": "Credentials from Password Stores",
    "T1560": "Archive Collected Data",
    "T1560.001": "Archive Collected Data: Archive via Utility",
    # T1562 retired in ATT&CK v19; T1562.001 promoted to standalone T1685.
    "T1685": "Disable or Modify Tools",
    "T1564": "Hide Artifacts",
    "T1564.003": "Hide Artifacts: Hidden Window",
    "T1568": "Dynamic Resolution",
    "T1573": "Encrypted Channel",
    "T1620": "Reflective Code Loading",
    "T1574": "Hijack Execution Flow",
    "T1622": "Debugger Evasion",
    # Persistence / Defense Evasion coverage extension -- see
    # static/scripts/src/detectors/attck_mapper.py's TECHNIQUE_NAMES for
    # the matching detection-side entries.
    "T1546.010": "Event Triggered Execution: AppInit DLLs",
    "T1547.004": "Boot or Logon Autostart Execution: Winlogon Helper DLL",
    "T1547.005": "Boot or Logon Autostart Execution: Security Support Provider",
    "T1547.002": "Boot or Logon Autostart Execution: Authentication Package",
    "T1546.012": "Event Triggered Execution: Image File Execution Options Injection",
    "T1546.003": "Event Triggered Execution: Windows Management Instrumentation Event Subscription",
    "T1197": "BITS Jobs",
    # Moved out of Indicator Removal (T1070) into the new T1685 parent in
    # ATT&CK v19 (migrated 2026-08, was T1070.001).
    "T1685.005": "Disable or Modify Tools: Clear Windows Event Logs",
    "T1218.010": "System Binary Proxy Execution: Regsvr32",
    "T1218.005": "System Binary Proxy Execution: Mshta",
    "T1055.012": "Process Injection: Process Hollowing",
    # Credential Access / Collection coverage extension.
    "T1003.001": "OS Credential Dumping: LSASS Memory",
    "T1003.002": "OS Credential Dumping: Security Account Manager",
    "T1003.004": "OS Credential Dumping: LSA Secrets",
    "T1552.002": "Unsecured Credentials: Credentials in Registry",
    "T1552.004": "Unsecured Credentials: Private Keys",
    "T1555.004": "Credentials from Password Stores: Windows Credential Manager",
    "T1556.002": "Modify Authentication Process: Password Filter DLL",
    "T1040": "Network Sniffing",
    "T1125": "Video Capture",
    "T1114.001": "Email Collection: Local Email Collection",
    "T1039": "Data from Network Shared Drive",
    # Execution / Command and Control coverage extension.
    "T1059.001": "Command and Scripting Interpreter: PowerShell",
    "T1559.002": "Inter-Process Communication: Dynamic Data Exchange",
    "T1127.001": "Trusted Developer Utilities Proxy Execution: MSBuild",
    "T1569.002": "System Services: Service Execution",
    "T1102.002": "Web Service: Bidirectional Communication",
    "T1572": "Protocol Tunneling",
    "T1090.002": "Proxy: External Proxy",
    # Discovery coverage extension.
    "T1120": "Peripheral Device Discovery",
    "T1614.001": "System Location Discovery: System Language Discovery",
    "T1049": "System Network Connections Discovery",
    "T1087.001": "Account Discovery: Local Account",
    "T1018": "Remote System Discovery",
    "T1010": "Application Window Discovery",
    "T1518.001": "Software Discovery: Security Software Discovery",
    # 3rd validation round (2026-08-28), full E2E re-run after removing the
    # tier-1 STIX-bundle path and expanding Execution/Persistence/C2.
    "T1012": "Query Registry",
    # Impact coverage extension.
    "T1529": "System Shutdown/Reboot",
    "T1531": "Account Access Removal",
    "T1561.001": "Disk Wipe: Disk Content Wipe",
    "T1496": "Resource Hijacking",
    # Privilege Escalation / Exfiltration coverage extension.
    "T1134.001": "Access Token Manipulation: Token Impersonation/Theft",
    "T1134.002": "Access Token Manipulation: Create Process with Token",
    "T1134.003": "Access Token Manipulation: Make and Impersonate Token",
    "T1546.008": "Event Triggered Execution: Accessibility Features",
    "T1546.009": "Event Triggered Execution: AppCert DLLs",
    "T1547.014": "Boot or Logon Autostart Execution: Active Setup",
    "T1098": "Account Manipulation",
    "T1567.001": "Exfiltration Over Web Service: Exfiltration to Code Repository",
    "T1567.002": "Exfiltration Over Web Service: Exfiltration to Cloud Storage",
    "T1567.003": "Exfiltration Over Web Service: Exfiltration to Text Storage Sites",
    "T1567.004": "Exfiltration Over Web Service: Exfiltration Over Webhook",
    "T1048.003": "Exfiltration Over Alternative Protocol: Exfiltration Over Unencrypted Non-C2 Protocol",
    # 2nd validation round (2026-08-28), after the CAPE agent-fingerprinting
    # fix restored real dynamic coverage — new technique IDs surfaced across
    # the 3 samples that weren't present in the first, degraded-dynamic run.
    "T1016": "System Network Configuration Discovery",
    "T1041": "Exfiltration Over C2 Channel",
    "T1115": "Clipboard Data",
    "T1123": "Audio Capture",
    "T1132": "Data Encoding",
    "T1140": "Deobfuscate/Decode Files or Information",
    "T1201": "Password Policy Discovery",
    "T1518": "Software Discovery",
    "T1555.003": "Credentials from Password Stores: Credentials from Web Browsers",
    # Seen in resubmit-queue re-analysis of RoningLoader's dropped files
    # (2nd clean-clone validation, 2026-08-28).
    "T1134": "Access Token Manipulation",
    "T1056.001": "Input Capture: Keylogging",

    # Full-tactic expansion (2026-08-28) for Execution, Persistence, and
    # Command and Control -- the 3 tactics a sample detonated in a single
    # isolated guest VM can actually produce evidence for (unlike Lateral
    # Movement, Initial Access, Reconnaissance, and Resource Development,
    # which describe attacker-side or multi-host activity this pipeline's
    # methodology structurally can't observe). Sourced from MITRE's public
    # enterprise-attack.json (ATT&CK v19.2), transcribed once rather than
    # depending on a fetched bundle at runtime.
    "T1001": "Data Obfuscation",
    "T1001.001": "Data Obfuscation: Junk Data",
    "T1001.002": "Data Obfuscation: Steganography",
    "T1001.003": "Data Obfuscation: Protocol or Service Impersonation",
    "T1008": "Fallback Channels",
    "T1037": "Boot or Logon Initialization Scripts",
    "T1037.001": "Boot or Logon Initialization Scripts: Logon Script (Windows)",
    "T1037.002": "Boot or Logon Initialization Scripts: Login Hook",
    "T1037.003": "Boot or Logon Initialization Scripts: Network Logon Script",
    "T1037.004": "Boot or Logon Initialization Scripts: RC Scripts",
    "T1037.005": "Boot or Logon Initialization Scripts: Startup Items",
    "T1053.002": "Scheduled Task/Job: At",
    "T1053.003": "Scheduled Task/Job: Cron",
    "T1053.005": "Scheduled Task/Job: Scheduled Task",
    "T1053.006": "Scheduled Task/Job: Systemd Timers",
    "T1053.007": "Scheduled Task/Job: Container Orchestration Job",
    "T1059.002": "Command and Scripting Interpreter: AppleScript",
    "T1059.003": "Command and Scripting Interpreter: Windows Command Shell",
    "T1059.004": "Command and Scripting Interpreter: Unix Shell",
    "T1059.005": "Command and Scripting Interpreter: Visual Basic",
    "T1059.006": "Command and Scripting Interpreter: Python",
    "T1059.007": "Command and Scripting Interpreter: JavaScript",
    "T1059.008": "Command and Scripting Interpreter: Network Device CLI",
    "T1059.009": "Command and Scripting Interpreter: Cloud API",
    "T1059.010": "Command and Scripting Interpreter: AutoHotKey & AutoIT",
    "T1059.011": "Command and Scripting Interpreter: Lua",
    "T1059.012": "Command and Scripting Interpreter: Hypervisor CLI",
    "T1059.013": "Command and Scripting Interpreter: Container CLI/API",
    "T1071.001": "Application Layer Protocol: Web Protocols",
    "T1071.002": "Application Layer Protocol: File Transfer Protocols",
    "T1071.003": "Application Layer Protocol: Mail Protocols",
    "T1071.004": "Application Layer Protocol: DNS",
    "T1071.005": "Application Layer Protocol: Publish/Subscribe Protocols",
    "T1072": "Software Deployment Tools",
    "T1078": "Valid Accounts",
    "T1078.001": "Valid Accounts: Default Accounts",
    "T1078.002": "Valid Accounts: Domain Accounts",
    "T1078.003": "Valid Accounts: Local Accounts",
    "T1078.004": "Valid Accounts: Cloud Accounts",
    "T1090.001": "Proxy: Internal Proxy",
    "T1090.003": "Proxy: Multi-hop Proxy",
    "T1090.004": "Proxy: Domain Fronting",
    "T1092": "Communication Through Removable Media",
    "T1095": "Non-Application Layer Protocol",
    "T1098.001": "Account Manipulation: Additional Cloud Credentials",
    "T1098.002": "Account Manipulation: Additional Email Delegate Permissions",
    "T1098.003": "Account Manipulation: Additional Cloud Roles",
    "T1098.004": "Account Manipulation: SSH Authorized Keys",
    "T1098.005": "Account Manipulation: Device Registration",
    "T1098.006": "Account Manipulation: Additional Container Cluster Roles",
    "T1098.007": "Account Manipulation: Additional Local or Domain Groups",
    "T1102": "Web Service",
    "T1102.001": "Web Service: Dead Drop Resolver",
    "T1102.003": "Web Service: One-Way Communication",
    "T1104": "Multi-Stage Channels",
    "T1127": "Trusted Developer Utilities Proxy Execution",
    "T1127.002": "Trusted Developer Utilities Proxy Execution: ClickOnce",
    "T1127.003": "Trusted Developer Utilities Proxy Execution: JamPlus",
    "T1132.001": "Data Encoding: Standard Encoding",
    "T1132.002": "Data Encoding: Non-Standard Encoding",
    "T1133": "External Remote Services",
    "T1136": "Create Account",
    "T1136.001": "Create Account: Local Account",
    "T1136.002": "Create Account: Domain Account",
    "T1136.003": "Create Account: Cloud Account",
    "T1137": "Office Application Startup",
    "T1137.001": "Office Application Startup: Office Template Macros",
    "T1137.002": "Office Application Startup: Office Test",
    "T1137.003": "Office Application Startup: Outlook Forms",
    "T1137.004": "Office Application Startup: Outlook Home Page",
    "T1137.005": "Office Application Startup: Outlook Rules",
    "T1137.006": "Office Application Startup: Add-ins",
    "T1176": "Software Extensions",
    "T1176.001": "Software Extensions: Browser Extensions",
    "T1176.002": "Software Extensions: IDE Extensions",
    "T1203": "Exploitation for Client Execution",
    "T1204": "User Execution",
    "T1204.001": "User Execution: Malicious Link",
    "T1204.002": "User Execution: Malicious File",
    "T1204.003": "User Execution: Malicious Image",
    "T1204.004": "User Execution: Malicious Copy and Paste",
    "T1204.005": "User Execution: Malicious Library",
    "T1205": "Traffic Signaling",
    "T1205.001": "Traffic Signaling: Port Knocking",
    "T1205.002": "Traffic Signaling: Socket Filters",
    "T1219": "Remote Access Tools",
    "T1219.001": "Remote Access Tools: IDE Tunneling",
    "T1219.002": "Remote Access Tools: Remote Desktop Software",
    "T1219.003": "Remote Access Tools: Remote Access Hardware",
    "T1505": "Server Software Component",
    "T1505.001": "Server Software Component: SQL Stored Procedures",
    "T1505.002": "Server Software Component: Transport Agent",
    "T1505.003": "Server Software Component: Web Shell",
    "T1505.004": "Server Software Component: IIS Components",
    "T1505.005": "Server Software Component: Terminal Services DLL",
    "T1505.006": "Server Software Component: vSphere Installation Bundles",
    "T1525": "Implant Internal Image",
    "T1542": "Pre-OS Boot",
    "T1542.001": "Pre-OS Boot: System Firmware",
    "T1542.002": "Pre-OS Boot: Component Firmware",
    "T1542.004": "Pre-OS Boot: ROMMONkit",
    "T1542.005": "Pre-OS Boot: TFTP Boot",
    "T1543.001": "Create or Modify System Process: Launch Agent",
    "T1543.002": "Create or Modify System Process: Systemd Service",
    "T1543.004": "Create or Modify System Process: Launch Daemon",
    "T1543.005": "Create or Modify System Process: Container Service",
    "T1546": "Event Triggered Execution",
    "T1546.001": "Event Triggered Execution: Change Default File Association",
    "T1546.002": "Event Triggered Execution: Screensaver",
    "T1546.004": "Event Triggered Execution: Unix Shell Configuration Modification",
    "T1546.005": "Event Triggered Execution: Trap",
    "T1546.006": "Event Triggered Execution: LC_LOAD_DYLIB Addition",
    "T1546.007": "Event Triggered Execution: Netsh Helper DLL",
    "T1546.011": "Event Triggered Execution: Application Shimming",
    "T1546.013": "Event Triggered Execution: PowerShell Profile",
    "T1546.014": "Event Triggered Execution: Emond",
    "T1546.015": "Event Triggered Execution: Component Object Model Hijacking",
    "T1546.016": "Event Triggered Execution: Installer Packages",
    "T1546.017": "Event Triggered Execution: Udev Rules",
    "T1546.018": "Event Triggered Execution: Python Startup Hooks",
    "T1547.003": "Boot or Logon Autostart Execution: Time Providers",
    "T1547.006": "Boot or Logon Autostart Execution: Kernel Modules and Extensions",
    "T1547.007": "Boot or Logon Autostart Execution: Re-opened Applications",
    "T1547.008": "Boot or Logon Autostart Execution: LSASS Driver",
    "T1547.009": "Boot or Logon Autostart Execution: Shortcut Modification",
    "T1547.010": "Boot or Logon Autostart Execution: Port Monitors",
    "T1547.012": "Boot or Logon Autostart Execution: Print Processors",
    "T1547.013": "Boot or Logon Autostart Execution: XDG Autostart Entries",
    "T1547.015": "Boot or Logon Autostart Execution: Login Items",
    "T1554": "Compromise Host Software Binary",
    "T1556": "Modify Authentication Process",
    "T1556.001": "Modify Authentication Process: Domain Controller Authentication",
    "T1556.003": "Modify Authentication Process: Pluggable Authentication Modules",
    "T1556.004": "Modify Authentication Process: Network Device Authentication",
    "T1556.005": "Modify Authentication Process: Reversible Encryption",
    "T1556.006": "Modify Authentication Process: Multi-Factor Authentication",
    "T1556.007": "Modify Authentication Process: Hybrid Identity",
    "T1556.008": "Modify Authentication Process: Network Provider DLL",
    "T1556.009": "Modify Authentication Process: Conditional Access Policies",
    "T1559": "Inter-Process Communication",
    "T1559.001": "Inter-Process Communication: Component Object Model",
    "T1559.003": "Inter-Process Communication: XPC Services",
    "T1568.001": "Dynamic Resolution: Fast Flux DNS",
    "T1568.002": "Dynamic Resolution: Domain Generation Algorithms",
    "T1568.003": "Dynamic Resolution: DNS Calculation",
    "T1569": "System Services",
    "T1569.001": "System Services: Launchctl",
    "T1569.003": "System Services: Systemctl",
    "T1571": "Non-Standard Port",
    "T1573.001": "Encrypted Channel: Symmetric Cryptography",
    "T1573.002": "Encrypted Channel: Asymmetric Cryptography",
    "T1574.001": "Hijack Execution Flow: DLL",
    "T1574.004": "Hijack Execution Flow: Dylib Hijacking",
    "T1574.005": "Hijack Execution Flow: Executable Installer File Permissions Weakness",
    "T1574.006": "Hijack Execution Flow: Dynamic Linker Hijacking",
    "T1574.007": "Hijack Execution Flow: Path Interception by PATH Environment Variable",
    "T1574.008": "Hijack Execution Flow: Path Interception by Search Order Hijacking",
    "T1574.009": "Hijack Execution Flow: Path Interception by Unquoted Path",
    "T1574.010": "Hijack Execution Flow: Services File Permissions Weakness",
    "T1574.011": "Hijack Execution Flow: Services Registry Permissions Weakness",
    "T1574.012": "Hijack Execution Flow: COR_PROFILER",
    "T1574.013": "Hijack Execution Flow: KernelCallbackTable",
    "T1574.014": "Hijack Execution Flow: AppDomainManager",
    "T1609": "Container Administration Command",
    "T1610": "Deploy Container",
    "T1648": "Serverless Execution",
    "T1651": "Cloud Administration Command",
    "T1653": "Power Settings",
    "T1659": "Content Injection",
    "T1665": "Hide Infrastructure",
    "T1668": "Exclusive Control",
    "T1671": "Cloud Application Integration",
    "T1674": "Input Injection",
    "T1675": "ESXi Administration Command",
    "T1677": "Poisoned Pipeline Execution",
}


def resolve_technique_name(technique_id: str, verbose: bool = False) -> str:
    """Resolve a technique ID to its name, via the 2-tier fallback described in this module's docstring.

    Args:
        technique_id: MITRE technique ID, e.g. 'T1055'.
        verbose: Log a warning when falling back to the generic placeholder.

    Returns:
        The technique's name, or 'Unknown ATT&CK technique (<id>)' if not found anywhere.
    """
    if technique_id in TECHNIQUE_NAME_FALLBACK:
        return TECHNIQUE_NAME_FALLBACK[technique_id]

    if verbose:
        print(f"Warning: no name found for {technique_id}, using placeholder")
    return f"Unknown ATT&CK technique ({technique_id})"
